on: push
name: Create Slate Documentation on Push
jobs:
  slate-documentation:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Build documentation
      uses: Decathlon/slate-builder-action@v1.0.0
      env:
        DOC_BASE_FOLDER: "."
