name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test with Rake
      run: |
        git config user.name "${INPUT_GITHUB_ACTOR}"
        git config user.email "${INPUT_GITHUB_ACTOR}@users.noreply.github.com"
        gem install bundler
        bundle install --jobs 4 --retry 3
        ./deploy.sh
